# Generated by Django 5.2.3 on 2025-07-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_contend_song_content_alter_song_singer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='relese',
            new_name='release',
        ),
    ]
