# Generated by Django 5.2.3 on 2025-07-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_titme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='titme',
            new_name='title',
        ),
    ]
