# Generated by Django 5.2.3 on 2025-07-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='contend',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.singer'),
        ),
    ]
