# Generated by Django 5.2.3 on 2025-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_relese_song_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='titme',
            field=models.CharField(default='제목없음', max_length=50),
            preserve_default=False,
        ),
    ]
